version: "3.9"

services: 
  api:
    build: ./back-end
    ports: 
      - "3000:3000"
    depends_on: 
      - db
    container_name: express-api
    volumes: 
    - ./back-end:/code
  
  db:
    image: mongo
    ports: 
      - "27017:27017"
    container_name: mongoDB